version: "3.7"

services:
  server:
    build: ./backend/server
    ports:
      - 5562:5562
    #Â working_dir: /app
    # command: python server.py
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  webapp:
    image: node:10.10-alpine
    volumes:
      - ./webapp:/var/www/webapp:rw,cached
    ports:
      - 1337:1337
    command: yarn start
    working_dir: /var/www/webapp
